// <auto-generated />
namespace SocialStrata.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V41 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V41));
        
        string IMigrationMetadata.Id
        {
            get { return "201605221731063_V4.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
